name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: >-
      startsWith(github.actor, 'dependabot') || github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          pull-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          commit-title: title
      - name: Confirm auto-merge
        if: ${{ github.event.pull_request.auto_merge.enabled == true }}
        run: echo "Auto-merge enabled for PR #${{ github.event.pull_request.number }}"