name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.actor, 'dependabot') || github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          pull-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          commit-title: ${{ github.event.pull_request.title }}